language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install codecov
# command to run tests
script: coverage run -m unittest
# Upload coverage if build succeeds
after_success:
  - codecov