language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
- pip install codecov
script: coverage run -m unittest
after_success:
- codecov
deploy:
  provider: pypi
  user: "ahhhhmed"
  password:
    secure: dZVlAZr8UvKEsIGYD1jaSSmQHzMo4gYVa2D4X8EAEtfSMr9FE6w4pMDAExdRfvR42meoL9IbmanTlwLm9ak6GQscP2uh1hM69c7mKB9q3EN0CoZLqIh++3eRAd5s7O0Mms89a95hJYi0ybG0nED6JRSj4fU1Vm9zR3jPYiK5Gb+ca/wxJNOLC9/yglePexXuhx3GdlM6BrooZEyPenztc5zfRvLnMuNl9ndZjKAFYQQ/+k/uoLzjqR1cGnfD2kCz6XMHffHFkGIKt3CV+qaXwhlzJKycv++586h63MBzbA/t46fTKg367hJVFb37jnziziPn0/kVeuBHX7Wjm0H/oPNqPt8p9qxlgMhWcci3KWd9sq8QhPDYVSk5xyozsFDqUIjhKsmApOyoKsf/eWVuGv+aakbaMBOuZlpj43YVHIW13kbHL9VlCXPcLBbbquzlG1UFrQXacZ2tQBrW9r8XUylc4ERcFwJ5pAKhbzHa0JTKdULkZmNjnWLVNZOL2xfs0VRiiRcf4sns1jxmz3gDQtyLXy0x/554TLp4fMHsY+kxYw5gY+Q+yMHw4VpNfFuFHU8IiSsPntL9Q7gzGEziSgnGTzevgaG2Os+R9GSy2fFGDvy4U//LwkHjUa+gvPm6cy4goNlv45tBU6NYCMG3yU9K09bAx0mDgoHAwqT/Pvc=
  on:
    tags: true
    python: '3.6'
